In [4]:
import numpy as np
#Definimos la matriz T
T=np.array([[0,-0.25,0.25,-0.25],[-0.25,0,0.25,0.25],[0.2,0.2,0,-0.2],[-1/3,1/3,-1/3,0]])
c=np.array([-0.5,-0.25,0,1/3])
x=np.array([0,0,0,0]) #Vector de valores iniciales
erroraceptado=0.01
error=1
iteraciones=0
maxiter=int(input('introduzca numero de iteraciones'))
print('Iteraciones')
print("      x1           x2          x3          x4")
while error>erroraceptado and iteraciones<maxiter:
    iteraciones+=1
    resultado=np.dot(T,x)+c
    print(resultado)
    numerador=np.amax(abs((resultado-x)))
    denominador=np.amax(abs(resultado))
    error=numerador/denominador
    x=resultado
print()
print()
print('los valores buscados que dan solucion son:')
print("      x1           x2          x3          x4")
print(resultado)

introduzca numero de iteraciones15
Iteraciones
      x1           x2          x3          x4
[-0.5        -0.25        0.          0.33333333]
[-0.52083333 -0.04166667 -0.21666667  0.41666667]
[-0.64791667 -0.06979167 -0.19583333  0.56527778]
[-0.67282986  0.00434028 -0.25659722  0.59131944]
[-0.71306424  0.00188802 -0.25196181  0.64458912]
[-0.72460974  0.02642289 -0.27115307  0.65563802]
[-0.73830349  0.02727367 -0.27076497  0.6740619 ]
[-0.74302514  0.0354001  -0.27701834  0.67878071]
[-0.74779979  0.03619688 -0.27728115  0.68514786]


los valores buscados que dan solucion son:
      x1           x2          x3          x4
[-0.74779979  0.03619688 -0.27728115  0.68514786]
