In [2]:
import numpy as np
#Definimos la matriz T
T=np.array([[0,-0.5,0,0],[-0.5,0,0.4,0],[0,0.5,0,1/8],[0,0,1/5,0]])
c=np.array([6/10,2.5,-11/8,-2.2])
x=np.array([0,0,0,0]) #Vector de valores iniciales
erroraceptado=0.01
error=1
iteraciones=0
maxiter=int(input('introduzca numero de iteraciones'))
print('Iteraciones')
print("      x1           x2          x3          x4")
while error>erroraceptado and iteraciones<maxiter:
    iteraciones+=1
    resultado=np.dot(T,x)+c
    print(resultado)
    numerador=np.amax(abs((resultado-x)))
    denominador=np.amax(abs(resultado))
    error=numerador/denominador
    x=resultado
print()
print()
print('los valores buscados que dan solucion son:')
print("      x1           x2          x3          x4")
print(resultado)

introduzca numero de iteraciones15
Iteraciones
      x1           x2          x3          x4
[ 0.6    2.5   -1.375 -2.2  ]
[-0.65   1.65  -0.4   -2.475]
[-0.225     2.665    -0.859375 -2.28    ]
[-0.7325    2.26875  -0.3275   -2.371875]
[-0.534375    2.73525    -0.53710938 -2.2655    ]
[-0.767625    2.55234375 -0.2905625  -2.30742188]
[-0.67617187  2.7675875  -0.38725586 -2.2581125 ]
[-0.78379375  2.68318359 -0.27347031 -2.27745117]
[-0.7415918   2.78250875 -0.3180896  -2.25469406]
[-0.79125437  2.74356006 -0.26558238 -2.26361792]
[-0.77178003  2.78939423 -0.28617221 -2.25311648]
[-0.79469712  2.77142113 -0.26194244 -2.25723444]


los valores buscados que dan solucion son:
      x1           x2          x3          x4
[-0.79469712  2.77142113 -0.26194244 -2.25723444]
