In [3]:
import numpy as np
#Definimos la matriz T
T=np.array([[0,1/10,0],[1/10,0,2/10],[0,2/10,0]])
c=np.array([9/10,7/10,6/10])
x=np.array([0,0,0]) #Vector de valores iniciales
erroraceptado=0.01
error=1
iteraciones=0
maxiter=int(input('introduzca numero de iteraciones'))
print('Iteraciones')
print("  x1  x2  x3")
while error>erroraceptado and iteraciones<maxiter:
    iteraciones+=1
    resultado=np.dot(T,x)+c
    print(resultado)
    numerador=np.amax(abs((resultado-x)))
    denominador=np.amax(abs(resultado))
    error=numerador/denominador
    x=resultado
print()
print()
print('los valores buscados que dan solucion son:')
print("  x1      x2     x3")
print(resultado)

introduzca numero de iteraciones10
Iteraciones
  x1  x2  x3
[0.9 0.7 0.6]
[0.97 0.91 0.74]
[0.991 0.945 0.782]
[0.9945 0.9555 0.789 ]
[0.99555 0.95725 0.7911 ]


los valores buscados que dan solucion son:
  x1      x2     x3
[0.99555 0.95725 0.7911 ]
