In [10]:
import numpy as np
#Definimos la matriz T
T=np.array([[0,1/3,-1/3],[-3/6,0,-2/6],[-3/7,-3/7,0]])
c=np.array([1/3,0,4/7])
x=np.array([0,0,0]) #Vector de valores iniciales
erroraceptado=0.01
error=1
iteraciones=0
maxiter=int(input('introduzca numero de iteraciones'))
print('Iteraciones')
print("      x1           x2          x3")
while error>erroraceptado and iteraciones<maxiter:
    iteraciones+=1
    resultado=np.dot(T,x)+c
    print(resultado)
    numerador=np.amax(abs((resultado-x)))
    denominador=np.amax(abs(resultado))
    error=numerador/denominador
    x=resultado
print()
print()
print('los valores buscados que dan solucion son:')
print("      x1           x2          x3")
print(resultado)

introduzca numero de iteraciones10
Iteraciones
      x1           x2          x3
[0.33333333 0.         0.57142857]
[ 0.14285714 -0.35714286  0.42857143]
[ 0.07142857 -0.21428571  0.66326531]
[ 0.04081633 -0.25680272  0.63265306]
[ 0.03684807 -0.23129252  0.66399417]
[ 0.03490444 -0.23975543  0.6547619 ]
[ 0.03516089 -0.23570619  0.65922185]


los valores buscados que dan solucion son:
      x1           x2          x3
[ 0.03516089 -0.23570619  0.65922185]
